name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale issue alert.'
        stale-pr-message: 'Stale PR alert.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
